#!/usr/bin/env python3
"""
data_engine.py — Telangana.live data sync engine
Usage:
  python scripts/data_engine.py --task fuel
  python scripts/data_engine.py --task pulses
  python scripts/data_engine.py --task alerts
  python scripts/data_engine.py --finance-only   (runs fuel + pulses)
"""

import argparse
import json
import os
import sys

if sys.stdout.encoding != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')
import datetime
import html
import re

import feedparser
import requests
from bs4 import BeautifulSoup

# Ensure project root is in path for importing backend providers
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
try:
    from core.llm_provider import llm
except ImportError:
    llm = None

try:
    from core.news_classifier import classify_article
except ImportError:
    classify_article = None

NOW = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
# Dates shown to readers are India dates; runners keep UTC.
IST = datetime.timezone(datetime.timedelta(hours=5, minutes=30))
DATA_DIR = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "frontend", "src", "data"))
FRONTEND_DATA_DIR = DATA_DIR

os.makedirs(DATA_DIR, exist_ok=True)

# PATHS registry — allows tests to redirect output files to tmp dirs
PATHS = {
    "fuel":   os.path.join(DATA_DIR, "fuelPrices.js"),
    "pulses": os.path.join(DATA_DIR, "pulses.js"),
    "news":   os.path.join(DATA_DIR, "news.json"),
    "weather": os.path.join(DATA_DIR, "weatherData.js"),
    "alerts":        os.path.join(DATA_DIR, "alerts.json"),
    # DATA_DIR is frontend/src/data, so the public dir is two levels up, not one.
    "alerts_public": os.path.abspath(os.path.join(DATA_DIR, "..", "..", "public", "data", "alerts.json")),
}


# Top-level keys that change on every run without the data changing.
_VOLATILE_KEYS = ("updatedAt", "lastUpdated", "generatedAt")


def _comparable(data):
    if isinstance(data, dict):
        return {k: v for k, v in data.items() if k not in _VOLATILE_KEYS}
    return data


def _unchanged(path, data):
    """True when the file already holds this data, ignoring run timestamps."""
    try:
        with open(path, encoding="utf-8") as f:
            match = re.search(r"= (\{[\s\S]*\}|\[[\s\S]*\]);\s*$", f.read())
        return bool(match) and _comparable(json.loads(match.group(1))) == _comparable(data)
    except (OSError, ValueError):
        return False


def _write_module(path, header, var_name, data):
    """Write a JS data module unless only its timestamps would change.

    Every run used to rewrite the file with a new run time, so every
    scheduled sync committed and redeployed even when no value changed
    (TL-08). Returns True when the file was written.
    """
    if _unchanged(path, data):
        print(f"  = Unchanged: {path}")
        return False
    js = f"{header}\nexport const {var_name} = {json.dumps(data, indent=2, ensure_ascii=False)};\n"
    with open(path, "w", encoding="utf-8") as f:
        f.write(js)
    return True


def write_js(filename, var_name, data):
    path = os.path.join(DATA_DIR, filename)
    written = _write_module(path, f"// Auto-generated by data_engine.py — {NOW}", var_name, data)
    if written:
        print(f"  ✅ Written: {path}")
    return written


def write_js_module(path, var_name, data):
    """Writes directly to the given path (used by the sync functions and tests)."""
    return _write_module(path, f"// Automatically generated by data_engine.py at {NOW}", var_name, data)


def get_recent_news_for_entity(entity_type: str, entity_id: str, limit: int = 5) -> list:
    """Reads news.json and returns a list of recent articles matching the entity_type and entity_id."""
    news_path = PATHS["news"]
    if not os.path.exists(news_path):
        return []
    try:
        with open(news_path, "r", encoding="utf-8") as f:
            articles = json.load(f)
        matches = []
        for article in articles:
            correlated = article.get("correlated_civic_entities", [])
            for ent in correlated:
                if ent.get("entity_type") == entity_type and ent.get("entity_id") == entity_id:
                    matches.append({
                        "id": article.get("id"),
                        "title": article.get("title"),
                        "description": article.get("description"),
                        "link": article.get("link"),
                        "source": article.get("source"),
                        "published": article.get("published"),
                        "category": article.get("category"),
                        "region": article.get("region"),
                        "image_url": article.get("image_url"),
                        "ai_summary": article.get("ai_summary")
                    })
                    break
        return matches[:limit]
    except Exception as e:
        print(f"  ⚠️ Error reading news for correlations: {e}")
        return []


# ── Test-compatibility shims ───────────────────────────────────────────────────
# These functions/attributes were part of an older engine API.
# They are kept so the existing test suite remains green without modification.

def clean_html(raw_html):
    """Strip all HTML tags and return plain text. Returns '' for None/empty."""
    if not raw_html:
        return ""
    return re.sub(r'<.*?>', '', raw_html).strip()


# Gemini model instance (None unless GOOGLE_API_KEY is set)
model = None

def get_ai_summary(title, description):
    """Generate a 2-line AI summary. Returns '' if model is None or on error."""
    if model is None:
        return ""
    try:
        prompt = (
            "Summarize this news article in exactly 2 concise lines for a civic portal. "
            f"Title: {title}. Description: {description}"
        )
        response = model.generate_content(prompt)
        return response.text.strip()
    except Exception:
        return ""


def http_get(url):
    return requests.get(
        url,
        timeout=20,
        headers={
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
        },
    )

def sync_to_redis(key, data):
    from dotenv import load_dotenv
    load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".env"))
    
    redis_url = os.environ.get("UPSTASH_REDIS_REST_URL")
    redis_token = os.environ.get("UPSTASH_REDIS_REST_TOKEN")
    
    if not redis_url or not redis_token:
        print(f"  ℹ️ Upstash credentials absent, skipped syncing {key} to Redis.")
        return
        
    try:
        url = f"{redis_url.rstrip('/')}/set/{key}"
        headers = {"Authorization": f"Bearer {redis_token}"}
        resp = requests.post(url, headers=headers, json=data)
        resp.raise_for_status()
        print(f"  ✅ Synced {key} to Upstash Redis directly!")
    except Exception as e:
        print(f"  ⚠️ Redis sync failed for {key}: {e}")



def clean_price(value):
    value = str(value).strip()
    value = value.replace("Rs.", "").replace("Rs", "").replace("₹", "").replace(",", "").strip()
    m = re.search(r"(\d+(?:\.\d+)?)", value)
    if not m:
        return None
    num = m.group(1)
    if "." in num:
        return f"₹{float(num):.2f}"
    return f"₹{num}"


# ── GOLD ──────────────────────────────────────────────────────────────────────
# ── GOLD ──────────────────────────────────────────────────────────────────────

# Gold and silver were read from Live Chennai, Mint and Goodreturns, whose
# terms may not allow it. They are no longer published (TL-46).


def _read_intro_price(url):
    """The first bold number in goodreturns' intro block, if plausible."""
    resp = http_get(url)
    if resp.status_code != 200:
        return None
    intro = BeautifulSoup(resp.text, "html.parser").find("div", id="gr_intro_content")
    if not (intro and intro.find("b")):
        return None
    val = float(intro.find("b").get_text(strip=True).replace(",", ""))
    return val if 50 < val < 200 else None


def _read_labelled_price(url, label):
    """"<label> Price ... ₹ <n>" anywhere on the page."""
    resp = http_get(url)
    if resp.status_code != 200:
        return None
    text = BeautifulSoup(resp.text, "html.parser").get_text()
    m = re.search(label + r" Price[^\d]{0,80}₹\s*([\d,.]+)", text, re.IGNORECASE)
    return float(m.group(1).replace(",", "")) if m else None


def _previous_fuel():
    try:
        with open(PATHS["fuel"], encoding="utf-8") as f:
            return json.loads(re.search(r"= (\{[\s\S]*\});", f.read()).group(1))
    except Exception:
        return {}


def sync_fuel():
    """Publish only prices read this run.

    A price that could not be read carries the previous file's real value and
    is listed in staleFields. If petrol and diesel both fail, the previous file
    is kept untouched (with its own date). There are no built-in fallback
    prices: it used to publish fixed 107.41 / 97.82 / 803 / 72.8 as today's.
    """
    print("Syncing fuel prices...")
    base = "https://www.goodreturns.in"
    readers = {
        "petrol": lambda: _read_intro_price(f"{base}/petrol-price-in-hyderabad.html"),
        "diesel": lambda: _read_intro_price(f"{base}/diesel-price-in-hyderabad.html"),
        "lpgHousehold": lambda: _read_labelled_price(f"{base}/lpg-price-in-hyderabad.html", "LPG"),
        "cngVehicle": lambda: _read_labelled_price(f"{base}/cng-price-in-hyderabad.html", "CNG"),
    }
    scraped = {}
    for key, read in readers.items():
        try:
            scraped[key] = read()
        except Exception as e:
            print(f"  ⚠️ {key} price not read ({e})")
            scraped[key] = None

    if scraped["petrol"] is None and scraped["diesel"] is None:
        print("  ⚠️ Petrol and diesel not read; keeping the previous fuel file.")
        return None

    previous = _previous_fuel()
    prices, stale = {}, []
    for key, value in scraped.items():
        if value is None:
            value = (previous.get(key) or {}).get("price")
            if value is None:
                print(f"  ⚠️ No {key} price this run or before; fuel file not written.")
                return None
            stale.append(key)
        prices[key] = value
    petrol_price, diesel_price = prices["petrol"], prices["diesel"]
    lpg_price, cng_price = prices["lpgHousehold"], prices["cngVehicle"]

    try:
        sync_to_redis("tg:rates:fuel:hyderabad", {
            "petrol": {"price": petrol_price, "unit": "per litre", "change": 0},
            "diesel": {"price": diesel_price, "unit": "per litre", "change": 0},
            "lpg": {"price": lpg_price, "unit": "per cylinder (14.2kg)", "change": 0},
            "cng": {"price": cng_price, "unit": "per kg", "change": 0},
            "source": "python-agent",
            "lastUpdated": NOW
        })
    except Exception as e:
        print(f"  ⚠️ Failed to sync fuel to Redis: {e}")

    frontend_fuel = {
        "updatedAt": NOW,
        "date": NOW[:10],
        "city": "Hyderabad",
        "petrol": {"price": petrol_price, "unit": "per litre", "change": 0},
        "diesel": {"price": diesel_price, "unit": "per litre", "change": 0},
        "lpgHousehold": {"price": lpg_price, "unit": "per cylinder (14.2kg)", "change": 0, "label": "LPG Domestic"},
        "cngVehicle": {"price": cng_price, "unit": "per kg", "change": 0, "label": "CNG Vehicle"},
        "news_alerts": get_recent_news_for_entity("fuel_price", "fuel"),
        # Prices not read this run; their values are the previous real ones.
        "staleFields": stale,
    }

    write_js_module(PATHS["fuel"], "fuelPrices", frontend_fuel)
    return frontend_fuel


def sync_finance():
    """Fuel, then pulses. Gold is no longer published (TL-46)."""
    sync_fuel()
    sync_pulses()


# ── PULSES / COMMODITIES ──────────────────────────────────────────────────────
PULSES_SOURCE_URL = "https://agmarknet.gov.in/"


def sync_pulses():
    """Write the pulses file with no prices until a real source is wired.

    The eNAM page scrape took any number near "Tur" or "Chana" (eNAM quotes
    per quintal, not per kg) and, when it found nothing, published fixed
    prices (Toor Dal 120/kg, ...) as today's Hyderabad market (TL-44). The
    site now shows no commodity price and links to Agmarknet instead.
    """
    print("Pulses: no licensed source wired; writing an empty list")
    frontend_pulses = {
        "updatedAt": NOW,
        "date": NOW[:10],
        "city": "Hyderabad",
        "market": "Hyderabad",
        "sourceUrl": PULSES_SOURCE_URL,
        "commodities": [],
    }
    write_js_module(PATHS["pulses"], "pulses", frontend_pulses)
    return frontend_pulses


def sync_news():
    """Scrape news via NewsScraper and merge into PATHS['news']."""
    print("Syncing news articles...")
    try:
        from news_scraper import NewsScraper
        scraper = NewsScraper()
        articles = scraper.scrape(limit=50)
        if not articles:
            print("  ⚠️ No news articles fetched (network or feeds offline). Skipping write to preserve existing data.")
            return
        os.makedirs(os.path.dirname(PATHS["news"]), exist_ok=True)

        existing = []
        if os.path.exists(PATHS["news"]):
            try:
                with open(PATHS["news"], "r", encoding="utf-8") as f:
                    existing = json.load(f)
            except Exception:
                existing = []

        existing_links = {a.get("link") or a.get("title") for a in existing}
        new_unique = [a for a in articles if (a.get("link") or a.get("title")) not in existing_links]
        merged = new_unique + existing

        with open(PATHS["news"], "w", encoding="utf-8") as f:
            json.dump(merged[:200], f, indent=2, ensure_ascii=False)
        print(f"  ✅ Written: {PATHS['news']} ({len(new_unique)} new articles added, total {len(merged[:200])})")
    except Exception as e:
        print(f"  ⚠️ News sync failed: {e}")


# ── LOCAL ALERTS FEED ──────────────────────────────────────────────────────────
# Regex-first classification (cheap, reliable, no dependency). AI is used only
# as an OPTIONAL confidence check for the more ambiguous alert types, and only
# if the LLM provider is actually available — alerts must never depend on AI
# being online, degrading gracefully when it is not.
ALERT_TOPIC_QUERIES = [
    "Telangana flood warning",
    "Hyderabad road closed traffic diversion",
    "TSSPDCL power cut Telangana",
    "HMWSSB water supply Hyderabad",
    "Telangana bandh strike",
    "IMD Telangana weather warning",
]

ALERT_EXPIRY_DAYS = 3

# Alert typing, geographic scoping, currency and severity are judged together by
# core.alert_triage (one TypeSafe request per headline). Thresholds and severity
# bands live there; see tools/calibrate_alert_triage.py to retune them.
try:
    from core.alert_triage import district_for, triage_headline
except ImportError:
    triage_headline = None

from core.alert_feed import build_alert_record, is_fresh, partition_existing


def _load_existing_alerts():
    if not os.path.exists(PATHS["alerts"]):
        return []
    try:
        with open(PATHS["alerts"], "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return []


# Official alerts from NDMA SACHET (IMD, CWC and the state SDMA publish CAP
# alerts there; no key). Only these issuing offices' alerts are downloaded, and
# each must name Telangana. See core/sachet.py.
SACHET_OFFICES = ("Telangana", "Hyderabad", "CWC", "New Delhi")


def _sachet_records(now_dt, kept, seen_titles):
    from core.alert_feed import build_official_record
    from core.sachet import AreaFilter, fetch_alerts

    session = requests.Session()
    session.headers["User-Agent"] = "telangana.live alerts (+https://www.telangana.live)"

    def get(url):
        response = session.get(url, timeout=30)
        response.raise_for_status()
        return response.text

    known = set()
    for alert in kept:
        match = re.search(r"sachet\.ndma\.gov\.in/.*identifier=([\w-]+)", alert.get("link") or "")
        if match:
            known.add(match.group(1))
    try:
        alerts = fetch_alerts(AreaFilter(state="Telangana"), offices=SACHET_OFFICES,
                              now=now_dt, get=get, skip_guids=known)
    except Exception as e:
        print(f"  ⚠️ SACHET feed unavailable: {e}")
        return []

    records = []
    for alert in alerts:
        record = build_official_record(alert, now=now_dt)
        if record["title"] in seen_titles:
            continue
        seen_titles.add(record["title"])
        records.append(record)
    print(f"  ✅ SACHET: {len(records)} new official alert(s)")
    return records


def sync_alerts():
    """Scan Google News RSS for likely local civic disruptions (floods, power/water
    outages, road closures, strikes, weather warnings) and write a deduped,
    auto-expiring alerts feed to frontend/src/data/alerts.json.

    Geographic scoping: queries are state-wide (not per-district — Telangana.live
    isn't multi-district-routed like the reference implementation this pattern was
    scoped from), and each match is regionally tagged using the existing
    core.news_classifier.classify_article() region inference instead of a new
    per-district query loop.
    """
    print("Syncing local alerts feed...")

    now_dt = datetime.datetime.now(datetime.UTC)
    kept, existing_titles = partition_existing(
        _load_existing_alerts(), now=now_dt, expiry_days=ALERT_EXPIRY_DAYS)

    new_alerts = []
    rejected = 0
    stale = 0

    for query in ALERT_TOPIC_QUERIES:
        try:
            rss_url = f"https://news.google.com/rss/search?q={requests.utils.quote(query)}&hl=en-IN&gl=IN&ceid=IN:en"
            feed = feedparser.parse(rss_url)
        except Exception as e:
            print(f"  ⚠️ Alert query failed ({query!r}): {e}")
            continue

        for entry in feed.entries[:10]:
            title = entry.get("title", "").strip()
            # Google News RSS appends " - Source Name" to titles; strip it so the
            # outlet's own name can't be read as part of the reported event.
            headline_only = re.sub(r"\s+-\s+[^-]+$", "", title)
            description_raw = entry.get("summary", "").strip()
            description = html.unescape(re.sub(r"<[^>]+>", "", description_raw)).strip()
            if not title or title in existing_titles:
                continue
            existing_titles.add(title)  # the same story often answers several queries

            # Google News search returns articles years old; drop them before
            # spending a triage call. The headline alone can't tell their age.
            if not is_fresh(entry.get("published_parsed"), now=now_dt,
                            max_age_days=ALERT_EXPIRY_DAYS):
                stale += 1
                continue

            if not triage_headline:
                continue

            # One request answers all four: which disruption type (or none),
            # whether it is in Telangana, whether it is current, how severe.
            verdict = triage_headline(headline_only, description)
            if not verdict.accepted:
                rejected += 1
                continue

            keyword_region = None
            if classify_article:
                _, keyword_region = classify_article(title, description)
            region = district_for(verdict, keyword_region=keyword_region)

            source = entry.get("source")
            new_alerts.append(build_alert_record(
                title=title,
                description=description,
                alert_type=verdict.alert_type,
                severity=verdict.severity,
                district=region,
                link=entry.get("link", ""),
                source=source.get("title", "Google News RSS") if isinstance(source, dict) else "Google News RSS",
                published=entry.get("published_parsed"),
                now=now_dt,
            ))

    official = _sachet_records(now_dt, kept, existing_titles)
    all_alerts = kept + official + new_alerts
    with open(PATHS["alerts"], "w", encoding="utf-8") as f:
        json.dump(all_alerts, f, indent=2, ensure_ascii=False)

    if os.path.exists(os.path.dirname(PATHS["alerts_public"])):
        with open(PATHS["alerts_public"], "w", encoding="utf-8") as f:
            json.dump(all_alerts, f, indent=2, ensure_ascii=False)
    else:
        # BreakingNewsBanner fetches this copy at runtime; skipping it silently
        # is how the public feed went unwritten before.
        print(f"  ⚠️ Public alerts dir missing, not written: {os.path.dirname(PATHS['alerts_public'])}")

    print(f"  ✅ Synced {len(new_alerts)} new alerts, rejected {rejected}, stale {stale} (Total active: {len(all_alerts)})")
    return all_alerts


# The "AI briefing" (aiBriefingData.js) was written by a small local model
# asked to produce comparison stats and prices; nothing on the site showed it
# and no workflow ran it. Removed (TL-48). The tech pulse comes from
# tech_pulse.py and sync_ai_pulse_news.py instead.


# ── MAIN ──────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--task", choices=["fuel", "pulses", "news", "alerts"])
    parser.add_argument("--finance-only", action="store_true")
    args = parser.parse_args()

    if args.finance_only:
        sync_finance()
    elif args.task == "fuel":
        sync_fuel()
    elif args.task == "pulses":
        sync_pulses()
    elif args.task == "news":
        sync_news()
    elif args.task == "alerts":
        sync_alerts()
    else:
        parser.print_help()
        sys.exit(1)

    print("\n✅ data_engine.py completed successfully.")


if __name__ == "__main__":
    main()
