import { useState } from 'react';
import { weatherData } from '../data/weatherData';
import UpdatedAt from '../components/UpdatedAt';

// This page used to show a "30-day forecast" for every district generated by a
// random-number function seeded with April averages, including "today" (TL-47).
// It now shows the current reading for each district from the hourly weather
// job, and sends people to IMD for forecasts and warnings.

const DISTRICTS = Object.keys(weatherData).sort();
const IMD_URL = 'https://mausam.imd.gov.in/hyderabad/';

function Stat({ label, value }) {
    return (
        <div className="detail-box">
            <p className="text-[10px] text-text-muted uppercase tracking-wider">{label}</p>
            <p className="text-lg font-bold text-white">{value}</p>
        </div>
    );
}

export default function WeatherForecastPage() {
    const [district, setDistrict] = useState(DISTRICTS.includes('Hyderabad') ? 'Hyderabad' : DISTRICTS[0]);
    const now = weatherData[district];

    return (
        <div className="max-w-4xl mx-auto px-4 py-12 animate-fade-in space-y-6">
            <header className="space-y-3">
                <h1 className="text-3xl font-heading font-bold text-white">Weather in Telangana</h1>
                <p className="text-text-secondary">
                    Current conditions and air quality for each district. For forecasts and heat or rain warnings, see{' '}
                    <a href={IMD_URL} target="_blank" rel="noopener noreferrer" className="underline">IMD Hyderabad</a>.
                </p>
                <label className="block">
                    <span className="sr-only">District</span>
                    <select
                        value={district}
                        onChange={(e) => setDistrict(e.target.value)}
                        className="px-3 py-2 rounded-xl bg-white/5 border border-white/10 text-white text-sm"
                    >
                        {DISTRICTS.map((d) => <option key={d} value={d} className="bg-dark-bg">{d}</option>)}
                    </select>
                </label>
            </header>

            {now ? (
                <section className="glass-card p-5 space-y-4">
                    <div className="flex items-baseline justify-between gap-3">
                        <h2 className="text-xl font-bold text-white">{district}: {now.condition}</h2>
                        <UpdatedAt timestamp={now.observedAt} maxAgeHours={3} />
                    </div>
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                        <Stat label="Temperature" value={`${now.temp}°C`} />
                        <Stat label="Feels like" value={`${now.feelsLike}°C`} />
                        <Stat label="Humidity" value={`${now.humidity}%`} />
                        <Stat label="Wind" value={`${now.windSpeed} km/h`} />
                    </div>
                    {now.aqi != null && (
                        <p className="text-sm text-text-secondary">
                            Air quality: <strong style={{ color: now.aqiColor }}>AQI {now.aqi} ({now.aqiLabel})</strong>.{' '}
                            <span className="text-text-muted text-xs">{now.aqiSource}; a model estimate, not a station reading.</span>
                        </p>
                    )}
                    <p className="text-[11px] text-text-muted">Source: {now.source}. Weather data by Open-Meteo.com (CC BY 4.0).</p>
                </section>
            ) : (
                <p className="text-sm text-text-muted">No reading for {district} right now.</p>
            )}
        </div>
    );
}
