#!/usr/bin/env python3
"""
data_engine.py — Telangana.live data sync engine
Usage:
  python scripts/data_engine.py --task gold
  python scripts/data_engine.py --task fuel
  python scripts/data_engine.py --task pulses
  python scripts/data_engine.py --task ai_pulse
  python scripts/data_engine.py --finance-only   (runs gold + fuel + pulses)
"""

import argparse
import json
import os
import sys
import datetime
import re
import requests
from bs4 import BeautifulSoup

NOW = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "data")

os.makedirs(DATA_DIR, exist_ok=True)


def write_js(filename, var_name, data):
    path = os.path.join(DATA_DIR, filename)
    js = f"// Auto-generated by data_engine.py — {NOW}\nexport const {var_name} = {json.dumps(data, indent=2, ensure_ascii=False)};\n"
    with open(path, "w", encoding="utf-8") as f:
        f.write(js)
    print(f"  ✅ Written: {path}")


def http_get(url):
    return requests.get(
        url,
        timeout=20,
        headers={
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"
        },
    )


def clean_price(value):
    value = str(value).strip()
    value = value.replace("Rs.", "").replace("Rs", "").replace("₹", "").replace(",", "").strip()
    m = re.search(r"(\d+(?:\.\d+)?)", value)
    if not m:
        return None
    num = m.group(1)
    if "." in num:
        return f"₹{float(num):.2f}"
    return f"₹{num}"


# ── GOLD ──────────────────────────────────────────────────────────────────────
def sync_gold():
    print("Syncing gold rates...")
    rates = {}
    fallback = {
        "22K Gold (1g)": {"today": "₹14,100", "yesterday": "₹14,100"},
        "24K Gold (1g)": {"today": "₹14,805", "yesterday": "₹14,805"},
        "18K Gold (1g)": {"today": "₹11,462", "yesterday": "₹11,462"},
    }

    sources_tried = []

    try:
        url = "https://www.goodreturns.in/gold-rates/hyderabad.html"
        sources_tried.append(url)
        resp = http_get(url)
        resp.raise_for_status()
        html = resp.text

        patterns = [
            ("24K Gold (1g)", r"24\s*Carat.*?Per Gram.*?\|1\|₹?([\d,]+(?:\.\d+)?)\|₹?([\d,]+(?:\.\d+)?)\|"),
            ("22K Gold (1g)", r"22\s*Carat.*?Per Gram.*?\|1\|₹?([\d,]+(?:\.\d+)?)\|₹?([\d,]+(?:\.\d+)?)\|"),
            ("18K Gold (1g)", r"18\s*Carat.*?Per Gram.*?\|1\|₹?([\d,]+(?:\.\d+)?)\|₹?([\d,]+(?:\.\d+)?)\|"),
        ]

        for label, pattern in patterns:
            m = re.search(pattern, html, re.I | re.S)
            if m:
                rates[label] = {
                    "today": f"₹{m.group(1)}",
                    "yesterday": f"₹{m.group(2)}",
                }

        if not rates:
            soup = BeautifulSoup(html, "html.parser")
            page_text = soup.get_text(" ", strip=True)

            alt_patterns = [
                ("22K Gold (1g)", r"22K[^₹]{0,80}₹\s*([\d,]+(?:\.\d+)?)"),
                ("24K Gold (1g)", r"24K[^₹]{0,80}₹\s*([\d,]+(?:\.\d+)?)"),
                ("18K Gold (1g)", r"18K[^₹]{0,80}₹\s*([\d,]+(?:\.\d+)?)"),
            ]

            for label, pattern in alt_patterns:
                m = re.search(pattern, page_text, re.I)
                if m:
                    rates[label] = {
                        "today": f"₹{m.group(1)}",
                        "yesterday": f"₹{m.group(1)}",
                    }

    except Exception as e:
        print(f"  ⚠️ Gold scrape failed: {e}")

    if not rates:
        print("  ⚠️ No gold rows parsed, using fallback")
        rates = fallback

    write_js(
        "goldRates.js",
        "goldRates",
        {
            "updatedAt": NOW,
            "city": "Hyderabad",
            "source": "Goodreturns",
            "sourceUrl": sources_tried[0] if sources_tried else None,
            "rates": rates,
        },
    )


# ── FUEL ──────────────────────────────────────────────────────────────────────
def sync_fuel():
    print("Syncing fuel prices...")

    petrol = "₹108.20"
    diesel = "₹94.62"
    lpg = "₹803.00"

    try:
        url = "https://www.goodreturns.in/petrol-price-in-hyderabad.html"
        resp = http_get(url)
        resp.raise_for_status()
        html = resp.text
        soup = BeautifulSoup(html, "html.parser")
        text = soup.get_text(" ", strip=True)

        petrol_patterns = [
            r"Petrol Price in Hyderabad[^₹]{0,80}₹\s*([\d.]+)",
            r"petrol-rate-city[^₹]{0,80}₹\s*([\d.]+)",
        ]
        diesel_patterns = [
            r"Diesel Price in Hyderabad[^₹]{0,80}₹\s*([\d.]+)",
        ]

        for pattern in petrol_patterns:
            m = re.search(pattern, text, re.I)
            if m:
                petrol = clean_price(m.group(1)) or petrol
                break

        for pattern in diesel_patterns:
            m = re.search(pattern, text, re.I)
            if m:
                diesel = clean_price(m.group(1)) or diesel
                break

    except Exception as e:
        print(f"  ⚠️ Fuel scrape failed ({e}), using fallback values")

    prices = {
        "updatedAt": NOW,
        "city": "Hyderabad",
        "source": "Goodreturns + fallback",
        "petrol": {"price": petrol, "unit": "per litre"},
        "diesel": {"price": diesel, "unit": "per litre"},
        "lpg": {
            "price": lpg,
            "unit": "per 14.2kg cylinder",
            "note": "Fallback/manual until a reliable source is integrated",
        },
    }

    write_js("fuelPrices.js", "fuelPrices", prices)


# ── PULSES / COMMODITIES ──────────────────────────────────────────────────────
def sync_pulses():
    print("Syncing commodity (pulses) prices...")

    fallback_items = [
        {"name": "Toor Dal", "price": "₹120/kg", "change": "0"},
        {"name": "Chana Dal", "price": "₹95/kg", "change": "0"},
        {"name": "Moong Dal", "price": "₹110/kg", "change": "0"},
        {"name": "Urad Dal", "price": "₹130/kg", "change": "0"},
    ]

    items = []

    try:
        url = "https://enam.gov.in/web/dashboard/agmarknet"
        resp = http_get(url)
        resp.raise_for_status()
        soup = BeautifulSoup(resp.text, "html.parser")
        text = soup.get_text(" ", strip=True)

        commodity_map = [
            ("Toor Dal", ["Tur", "Toor"]),
            ("Chana Dal", ["Chana"]),
            ("Moong Dal", ["Moong"]),
            ("Urad Dal", ["Urad"]),
        ]

        for display_name, aliases in commodity_map:
            found = None
            for alias in aliases:
                m = re.search(rf"{alias}[^0-9₹]{{0,80}}(\d{{2,5}}(?:\.\d+)?)", text, re.I)
                if m:
                    found = m.group(1)
                    break
            if found:
                items.append({"name": display_name, "price": f"₹{found}/kg", "change": "0"})

    except Exception as e:
        print(f"  ⚠️ Pulses scrape failed ({e}), using fallback values")

    if not items:
        items = fallback_items

    pulses = {
        "updatedAt": NOW,
        "market": "Hyderabad",
        "source": "Agmarknet/eNAM fallback",
        "items": items,
    }

    write_js("pulses.js", "pulses", pulses)


# ── AI PULSE BRIEFING ─────────────────────────────────────────────────────────
def sync_ai_pulse():
    print("Syncing AI pulse briefing...")
    api_key = os.environ.get("GOOGLE_API_KEY", "")
    briefing = {"updatedAt": NOW, "items": []}

    if api_key:
        try:
            import google.generativeai as genai
            genai.configure(api_key=api_key)
            model = genai.GenerativeModel("gemini-1.5-flash")
            prompt = (
                "Give me 3 short AI news headlines relevant to India for today "
                "in JSON array format: [{\"headline\": \"\", \"summary\": \"\"}]"
            )
            resp = model.generate_content(prompt)
            text = resp.text.strip().strip("```json").strip("```").strip()
            briefing["items"] = json.loads(text)
            print("  ✅ Gemini AI briefing fetched")
        except Exception as e:
            print(f"  ⚠️ Gemini failed ({e}), using placeholder")
            briefing["items"] = _placeholder_ai_items()
    else:
        print("  ℹ️ GOOGLE_API_KEY not set — using placeholder content")
        briefing["items"] = _placeholder_ai_items()

    write_js("aiBriefingData.js", "aiBriefingData", briefing)


def _placeholder_ai_items():
    return [
        {"headline": "India AI Mission allocates ₹500Cr for GPU clusters",
         "summary": "MeitY announces new compute infra under IndiaAI Mission."},
        {"headline": "Hyderabad emerges as top AI hiring hub in South Asia",
         "summary": "NASSCOM report shows 40% YoY growth in AI roles in Hyderabad."},
        {"headline": "ISRO uses ML models for crop yield prediction in Telangana",
         "summary": "Pilot covers 12 districts with 85% prediction accuracy."},
    ]


# ── MAIN ──────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--task", choices=["gold", "fuel", "pulses", "ai_pulse"])
    parser.add_argument("--finance-only", action="store_true")
    args = parser.parse_args()

    if args.finance_only:
        sync_gold()
        sync_fuel()
        sync_pulses()
    elif args.task == "gold":
        sync_gold()
    elif args.task == "fuel":
        sync_fuel()
    elif args.task == "pulses":
        sync_pulses()
    elif args.task == "ai_pulse":
        sync_ai_pulse()
    else:
        parser.print_help()
        sys.exit(1)

    print("\n✅ data_engine.py completed successfully.")


if __name__ == "__main__":
    main()
