import os
import json
import re
import sys
import time
from datetime import datetime

# Resolve repo root so that PATHS are correct regardless of the working
# directory when this script is invoked (e.g. via subprocess from main.py).
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Optional imports — gracefully degrade if missing
try:
    import requests
    from bs4 import BeautifulSoup
except ImportError:
    print("WARNING: requests/beautifulsoup4 not installed. Install with: pip install requests beautifulsoup4")
    requests = None

try:
    import feedparser
except ImportError:
    print("WARNING: feedparser not installed. Install with: pip install feedparser")
    feedparser = None

try:
    import google.generativeai as genai
except ImportError:
    genai = None

# Add scripts dir to path so news_scraper can be imported
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from news_scraper import NewsScraper

# Configuration
GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY")
model = None
if GOOGLE_API_KEY and genai:
    genai.configure(api_key=GOOGLE_API_KEY)
    model = genai.GenerativeModel('gemini-1.5-flash')
else:
    print("WARNING: GOOGLE_API_KEY not found or google-generativeai not installed. AI features disabled.")

PATHS = {
    "news":     os.path.join(_REPO_ROOT, "src", "data", "news.json"),
    "gold":     os.path.join(_REPO_ROOT, "src", "data", "goldRates.js"),
    "fuel":     os.path.join(_REPO_ROOT, "src", "data", "fuelPrices.js"),
    "pulses":   os.path.join(_REPO_ROOT, "src", "data", "pulses.js"),
    "ai_pulse": os.path.join(_REPO_ROOT, "src", "data", "aiBriefingData.js"),
}

# --- Utils ---
def write_js_module(path, var_name, data):
    """Writes a dictionary as an ES module constant."""
    content = f"// Automatically generated by data_engine.py at {datetime.now().isoformat()}\n"
    content += f"export const {var_name} = {json.dumps(data, indent=2, ensure_ascii=False)};\n"
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

def clean_html(raw_html):
    if not raw_html: return ""
    return re.sub('<.*?>', '', raw_html).strip()

def get_ai_summary(title, description):
    if not model: return ""
    prompt = f"Summarize this news article in exactly 2 concise lines for a civic portal. Title: {title}. Description: {description}"
    try:
        response = model.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        print(f"AI Error: {e}")
        return ""

# --- Scrapers ---

def sync_gold_silver():
    """Sync gold and silver rates from goodreturns.in (Hyderabad)."""
    if not requests:
        print("SKIP: sync_gold_silver requires requests/beautifulsoup4. Install with: pip install requests beautifulsoup4")
        return
    print("Syncing Gold & Silver Rates...")
    gold_url = "https://www.goodreturns.in/gold-rates-in-hyderabad.html"
    headers = {'User-Agent': 'Mozilla/5.0'}

    try:
        res = requests.get(gold_url, headers=headers, timeout=10)
        soup = BeautifulSoup(res.text, 'html.parser')
        text = soup.get_text()

        gold22 = re.search(r"22\s*K[\s\S]{0,100}Rs\.?\s*([\d,]+)", text, re.I)
        gold24 = re.search(r"24\s*K[\s\S]{0,100}Rs\.?\s*([\d,]+)", text, re.I)
        silver = re.search(r"Silver[\s\S]{0,100}Rs\.?\s*([\d,]+)", text, re.I)
        # Matches both ₹ and Rs. price prefixes used by Indian financial sites
        _CURR = r"(?:₹|Rs\.?\s*)"
        gold22 = re.search(rf"22\s*[Kk](?:arat)?\b[\s\S]{{0,300}}{_CURR}([\d,]{{4,}})", text, re.I)
        gold24 = re.search(rf"24\s*[Kk](?:arat)?\b[\s\S]{{0,300}}{_CURR}([\d,]{{4,}})", text, re.I)
        silver = re.search(rf"[Ss]ilver\b[\s\S]{{0,300}}{_CURR}([\d,]{{2,}})", text, re.I)

        def p(m): return float(m.group(1).replace(',', '')) if m else 0

        g22 = p(gold22)
        g24 = p(gold24)
        sil_raw = p(silver)
        # GoodReturns may show silver per gram (~80-120) or per kg (~80000-120000).
        # Divide by 1000 only when the raw value suggests a per-kg figure.
        sil = sil_raw / 1000 if sil_raw > 1000 else sil_raw

        # Try to maintain history
        history = []
        if os.path.exists(PATHS["gold"]):
            try:
                with open(PATHS["gold"], "r", encoding="utf-8") as f:
                    old_content = f.read()
                    history_match = re.search(r'"history":\s*(\[[\s\S]*?\])', old_content)
                    if history_match:
                        history = json.loads(history_match.group(1))
            except Exception as history_err:
                print(f"History retrieval error: {history_err}")

        current_entry = {
            "date": datetime.now().strftime("%Y-%m-%d"),
            "gold22k": g22 if g22 > 1000 else 7180,
            "gold24k": g24 if g24 > 1000 else 7830,
            "silver": sil if sil > 50 else 96.50
        }

        # Compute day-over-day change using the most recent previous entry
        prev_entry = history[-1] if history else None
        change22k = round(current_entry["gold22k"] - prev_entry["gold22k"], 2) if prev_entry else 0
        change24k = round(current_entry["gold24k"] - prev_entry["gold24k"], 2) if prev_entry else 0
        change_sil = round(current_entry["silver"] - prev_entry["silver"], 2) if prev_entry else 0

        # Avoid duplicate dates in history
        history = [h for h in history if h.get("date") != current_entry["date"]]
        history.append(current_entry)
        history = history[-7:]  # Keep last 7 days

        gold_data = {
            "city": "Hyderabad",
            "date": datetime.now().strftime("%Y-%m-%d"),
            "gold22k": {"price": current_entry["gold22k"], "change": change22k, "unit": "₹/gram"},
            "gold24k": {"price": current_entry["gold24k"], "change": change24k, "unit": "₹/gram"},
            "silver": {"price": current_entry["silver"], "change": change_sil, "unit": "₹/gram"},
            "history": history
        }
        write_js_module(PATHS["gold"], "goldRates", gold_data)
        print(f"Gold 22K: ₹{current_entry['gold22k']}/g, 24K: ₹{current_entry['gold24k']}/g, Silver: ₹{current_entry['silver']}/g")
    except Exception as e:
        print(f"Gold Scrape Error: {e}")


def sync_fuel():
    """Sync petrol/diesel/LPG/CNG prices from goodreturns.in (Hyderabad)."""
    if not requests:
        print("SKIP: sync_fuel requires requests/beautifulsoup4. Install with: pip install requests beautifulsoup4")
        return
    print("Syncing Fuel Prices...")
    fuel_url = "https://www.goodreturns.in/fuel-price/hyderabad.html"
    headers = {'User-Agent': 'Mozilla/5.0'}

    try:
        res = requests.get(fuel_url, headers=headers, timeout=10)
        soup = BeautifulSoup(res.text, 'html.parser')
        text = soup.get_text()

        petrol = re.search(r"Petrol[\s\S]*?Rs\.\s*([\d.]+)", text, re.I)
        diesel = re.search(r"Diesel[\s\S]*?Rs\.\s*([\d.]+)", text, re.I)

        p_price = float(petrol.group(1)) if petrol else 107.41
        d_price = float(diesel.group(1)) if diesel else 97.82

        fuel_data = {
            "city": "Hyderabad",
            "date": datetime.now().strftime("%Y-%m-%d"),
            "petrol": {
                "price": p_price,
                "change": 0,
                "unit": "₹/litre",
                "taxBreakup": {
                    "basePrice": round(p_price * 0.53, 2),
                    "centralExcise": 19.90,
                    "stateVAT": round(p_price * 0.35, 2),
                    "dealerCommission": 3.80,
                }
            },
            "diesel": {
                "price": d_price,
                "change": 0,
                "unit": "₹/litre",
                "taxBreakup": {
                    "basePrice": round(d_price * 0.58, 2),
                    "centralExcise": 15.80,
                    "stateVAT": round(d_price * 0.27, 2),
                    "dealerCommission": 2.60,
                }
            },
            "lpgHousehold": {
                "label": "LPG (Household 14.2kg)",
                "price": 803.00,
                "change": 0,
                "unit": "₹/cylinder",
                "taxBreakup": {
                    "basePrice": 764.76,
                    "gst": 38.24,  # 5% GST on domestic LPG
                    "distributorCommission": 64.00,
                }
            },
            "cngVehicle": {
                "label": "Auto CNG (Vehicle)",
                "price": 60.86,
                "change": 0,
                "unit": "₹/kg",
                "taxBreakup": {
                    "basePrice": 48.68,
                    "gst": 7.30,  # 12% GST on CNG typically
                    "excise": 4.88,
                }
            }
        }
        write_js_module(PATHS["fuel"], "fuelPrices", fuel_data)
        print(f"Petrol: ₹{p_price}/L, Diesel: ₹{d_price}/L")
    except Exception as e:
        print(f"Fuel Scrape Error: {e}")


def sync_finance():
    """Backward-compatible wrapper: sync both gold/silver and fuel prices."""
    sync_gold_silver()
    sync_fuel()

def sync_pulses():
    print("Syncing pulses (Commodity) Rates...")
    # Using a representative set of essential commodities for Hyderabad
    # In a production agentic system, this could be fetched from specialized ag-market APIs
    data = {
        "city": "Hyderabad",
        "date": datetime.now().strftime("%Y-%m-%d"),
        "commodities": [
            {"name": "Toor Dal", "price": 164.00, "unit": "kg", "change": 2.0},
            {"name": "Moong Dal", "price": 118.00, "unit": "kg", "change": -1.5},
            {"name": "Urad Dal", "price": 128.00, "unit": "kg", "change": 0.0},
            {"name": "Chana Dal", "price": 84.00, "unit": "kg", "change": 1.0},
            {"name": "Rice (Sona Masuri)", "price": 62.00, "unit": "kg", "change": 0.5},
            {"name": "Sugar", "price": 44.00, "unit": "kg", "change": 0.0}
        ]
    }
    write_js_module(PATHS["pulses"], "pulsesData", data)

def sync_news():
    print("Syncing News via NewsScraper...")
    scraper = NewsScraper()
    all_news = scraper.scrape(limit=10)
    
    with open(PATHS["news"], "w", encoding="utf-8") as f:
        json.dump(all_news, f, indent=2, ensure_ascii=False)
    print(f"News sync complete. {len(all_news)} items saved.")

def sync_ai_pulse():
    print("Synthesizing AI Pulse Briefing...")
    if not model: return
    
    # In a real environment, we'd search first. Here we use Gemini to synthesize broad daily trends.
    today = datetime.now().strftime("%B %d, %Y")
    today_iso = datetime.now().strftime("%Y-%m-%d")
    prompt = (
        "Act as a tech lead for a civic portal. Analyze the current date (" + today + ") "
        "and synthesize a daily briefing on AI model releases (OpenAI, Anthropic, Google, Nvidia, GitHub). "
        "Focus on Coding, Agentic capability, and Long-context. "
        "Output a JSON object that matches telangana.live schema: "
        '{"date": "' + today_iso + '", '
        '"executiveBrief": [{id, title, description, gainedGround, trend}], '
        '"comparisonStats": [{provider, model, codingScore, agenticScore, contextWindow, pricePer1M, priceChange, status, color, glow}], '
        '"deprecations": [{model, provider, date, replacement}]} '
        "Make the content professional, high-impact, and futuristic."
    )
    try:
        response = model.generate_content(prompt)
        # Extract JSON from markdown response
        json_str = re.search(r"\{[\s\S]*\}", response.text).group(0)
        data = json.loads(json_str)
        write_js_module(PATHS["ai_pulse"], "aiBriefingData", data)
    except Exception as e:
        print(f"AI Pulse Error: {e}")

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Sync data for telangana.live")
    parser.add_argument(
        '--task',
        choices=['all', 'news', 'gold', 'fuel', 'pulses', 'ai_pulse'],
        default='all',
        help="Which data to sync (default: all)",
    )
    args = parser.parse_args()

    TASK_MAP = {
        'all':      [("Gold/Silver & Fuel", sync_finance), ("Pulses", sync_pulses), ("News", sync_news), ("AI Pulse", sync_ai_pulse)],
        'news':     [("News", sync_news)],
        'gold':     [("Gold/Silver", sync_gold_silver)],
        'fuel':     [("Fuel", sync_fuel)],
        'pulses':   [("Pulses", sync_pulses)],
        'ai_pulse': [("AI Pulse", sync_ai_pulse)],
    }

    tasks = TASK_MAP[args.task]
    parser = argparse.ArgumentParser(description="Telangana Live data sync engine")
    parser.add_argument(
        "--finance-only",
        action="store_true",
        help="Sync only gold and fuel rates (skip news and AI pulse)",
    )
    args = parser.parse_args()

    if args.finance_only:
        tasks = [("Finance", sync_finance), ("Pulses", sync_pulses)]
    else:
        tasks = [("Finance", sync_finance), ("Pulses", sync_pulses), ("News", sync_news), ("AI Pulse", sync_ai_pulse)]

    errors = []
    for name, fn in tasks:
        try:
            fn()
        except Exception as e:
            print(f"ERROR in {name}: {e}")
            errors.append(name)
    if errors:
        print(f"\nSync completed with errors in: {', '.join(errors)}")
    else:
        print(f"\nSynchronization complete ({args.task}).")
        print("\nSync complete." if args.finance_only else "\nFull Synchronization Complete.")
