#!/usr/bin/env python3
"""
weather_scraper.py — Fetches weather for major Telangana cities
Writes: src/data/weatherData.js
Requires: OWM_API_KEY env var (OpenWeatherMap free tier)
"""

import os, json, requests, datetime

NOW  = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
API  = os.environ.get("OWM_API_KEY", "")
DATA = os.path.join(os.path.dirname(__file__), "..", "src", "data")
os.makedirs(DATA, exist_ok=True)

CITIES = [
    {"name": "Hyderabad",   "id": 1269843},
    {"name": "Warangal",    "id": 1253102},
    {"name": "Nizamabad",   "id": 1262179},
    {"name": "Karimnagar",  "id": 1268680},
    {"name": "Khammam",     "id": 1267929},
]

def fetch_city(city_id):
    url = f"https://api.openweathermap.org/data/2.5/weather?id={city_id}&appid={API}&units=metric"
    r = requests.get(url, timeout=10)
    r.raise_for_status()
    d = r.json()
    return {
        "temp":        round(d["main"]["temp"]),
        "feels_like":  round(d["main"]["feels_like"]),
        "humidity":    d["main"]["humidity"],
        "condition":   d["weather"][0]["main"],
        "description": d["weather"][0]["description"].title(),
        "icon":        d["weather"][0]["icon"],
        "wind_kph":    round(d["wind"]["speed"] * 3.6),
    }

weather_data = {"updatedAt": NOW, "cities": {}}

for city in CITIES:
    try:
        weather_data["cities"][city["name"]] = fetch_city(city["id"])
        print(f"  ✅ {city['name']}")
    except Exception as e:
        print(f"  ⚠️  {city['name']} failed: {e}")
        weather_data["cities"][city["name"]] = {
            "temp": "--", "humidity": "--", "condition": "N/A",
            "description": "Data unavailable", "icon": "01d", "wind_kph": "--"
        }

out = os.path.join(DATA, "weatherData.js")
js  = f"// Auto-generated by weather_scraper.py — {NOW}\nexport const weatherData = {json.dumps(weather_data, indent=2, ensure_ascii=False)};\n"
with open(out, "w", encoding="utf-8") as f:
    f.write(js)

print(f"\n✅ weatherData.js written to {out}")
